/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package me.mh.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class BdPerson extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7715986458037798122L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BdPerson\",\"namespace\":\"me.mh.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"username\",\"type\":[\"string\",\"null\"]},{\"name\":\"email_address\",\"type\":[\"string\",\"null\"]},{\"name\":\"phone_number\",\"type\":[\"string\",\"null\"]},{\"name\":\"first_name\",\"type\":[\"string\",\"null\"]},{\"name\":\"last_name\",\"type\":[\"string\",\"null\"]},{\"name\":\"middle_name\",\"type\":[\"string\",\"null\"]},{\"name\":\"sex\",\"type\":[\"string\",\"null\"]},{\"name\":\"birthdate\",\"type\":[\"string\",\"null\"]},{\"name\":\"join_date\",\"type\":[\"string\",\"null\"]},{\"name\":\"previous_logins\",\"type\":[\"int\",\"null\"]},{\"name\":\"last_ip\",\"type\":[\"string\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<BdPerson> ENCODER =
      new BinaryMessageEncoder<BdPerson>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BdPerson> DECODER =
      new BinaryMessageDecoder<BdPerson>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<BdPerson> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<BdPerson> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<BdPerson> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<BdPerson>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this BdPerson to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a BdPerson from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a BdPerson instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static BdPerson fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int id;
  private java.lang.CharSequence username;
  private java.lang.CharSequence email_address;
  private java.lang.CharSequence phone_number;
  private java.lang.CharSequence first_name;
  private java.lang.CharSequence last_name;
  private java.lang.CharSequence middle_name;
  private java.lang.CharSequence sex;
  private java.lang.CharSequence birthdate;
  private java.lang.CharSequence join_date;
  private java.lang.Integer previous_logins;
  private java.lang.CharSequence last_ip;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BdPerson() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param username The new value for username
   * @param email_address The new value for email_address
   * @param phone_number The new value for phone_number
   * @param first_name The new value for first_name
   * @param last_name The new value for last_name
   * @param middle_name The new value for middle_name
   * @param sex The new value for sex
   * @param birthdate The new value for birthdate
   * @param join_date The new value for join_date
   * @param previous_logins The new value for previous_logins
   * @param last_ip The new value for last_ip
   */
  public BdPerson(java.lang.Integer id, java.lang.CharSequence username, java.lang.CharSequence email_address, java.lang.CharSequence phone_number, java.lang.CharSequence first_name, java.lang.CharSequence last_name, java.lang.CharSequence middle_name, java.lang.CharSequence sex, java.lang.CharSequence birthdate, java.lang.CharSequence join_date, java.lang.Integer previous_logins, java.lang.CharSequence last_ip) {
    this.id = id;
    this.username = username;
    this.email_address = email_address;
    this.phone_number = phone_number;
    this.first_name = first_name;
    this.last_name = last_name;
    this.middle_name = middle_name;
    this.sex = sex;
    this.birthdate = birthdate;
    this.join_date = join_date;
    this.previous_logins = previous_logins;
    this.last_ip = last_ip;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return username;
    case 2: return email_address;
    case 3: return phone_number;
    case 4: return first_name;
    case 5: return last_name;
    case 6: return middle_name;
    case 7: return sex;
    case 8: return birthdate;
    case 9: return join_date;
    case 10: return previous_logins;
    case 11: return last_ip;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: username = (java.lang.CharSequence)value$; break;
    case 2: email_address = (java.lang.CharSequence)value$; break;
    case 3: phone_number = (java.lang.CharSequence)value$; break;
    case 4: first_name = (java.lang.CharSequence)value$; break;
    case 5: last_name = (java.lang.CharSequence)value$; break;
    case 6: middle_name = (java.lang.CharSequence)value$; break;
    case 7: sex = (java.lang.CharSequence)value$; break;
    case 8: birthdate = (java.lang.CharSequence)value$; break;
    case 9: join_date = (java.lang.CharSequence)value$; break;
    case 10: previous_logins = (java.lang.Integer)value$; break;
    case 11: last_ip = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public int getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(int value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'username' field.
   * @return The value of the 'username' field.
   */
  public java.lang.CharSequence getUsername() {
    return username;
  }


  /**
   * Sets the value of the 'username' field.
   * @param value the value to set.
   */
  public void setUsername(java.lang.CharSequence value) {
    this.username = value;
  }

  /**
   * Gets the value of the 'email_address' field.
   * @return The value of the 'email_address' field.
   */
  public java.lang.CharSequence getEmailAddress() {
    return email_address;
  }


  /**
   * Sets the value of the 'email_address' field.
   * @param value the value to set.
   */
  public void setEmailAddress(java.lang.CharSequence value) {
    this.email_address = value;
  }

  /**
   * Gets the value of the 'phone_number' field.
   * @return The value of the 'phone_number' field.
   */
  public java.lang.CharSequence getPhoneNumber() {
    return phone_number;
  }


  /**
   * Sets the value of the 'phone_number' field.
   * @param value the value to set.
   */
  public void setPhoneNumber(java.lang.CharSequence value) {
    this.phone_number = value;
  }

  /**
   * Gets the value of the 'first_name' field.
   * @return The value of the 'first_name' field.
   */
  public java.lang.CharSequence getFirstName() {
    return first_name;
  }


  /**
   * Sets the value of the 'first_name' field.
   * @param value the value to set.
   */
  public void setFirstName(java.lang.CharSequence value) {
    this.first_name = value;
  }

  /**
   * Gets the value of the 'last_name' field.
   * @return The value of the 'last_name' field.
   */
  public java.lang.CharSequence getLastName() {
    return last_name;
  }


  /**
   * Sets the value of the 'last_name' field.
   * @param value the value to set.
   */
  public void setLastName(java.lang.CharSequence value) {
    this.last_name = value;
  }

  /**
   * Gets the value of the 'middle_name' field.
   * @return The value of the 'middle_name' field.
   */
  public java.lang.CharSequence getMiddleName() {
    return middle_name;
  }


  /**
   * Sets the value of the 'middle_name' field.
   * @param value the value to set.
   */
  public void setMiddleName(java.lang.CharSequence value) {
    this.middle_name = value;
  }

  /**
   * Gets the value of the 'sex' field.
   * @return The value of the 'sex' field.
   */
  public java.lang.CharSequence getSex() {
    return sex;
  }


  /**
   * Sets the value of the 'sex' field.
   * @param value the value to set.
   */
  public void setSex(java.lang.CharSequence value) {
    this.sex = value;
  }

  /**
   * Gets the value of the 'birthdate' field.
   * @return The value of the 'birthdate' field.
   */
  public java.lang.CharSequence getBirthdate() {
    return birthdate;
  }


  /**
   * Sets the value of the 'birthdate' field.
   * @param value the value to set.
   */
  public void setBirthdate(java.lang.CharSequence value) {
    this.birthdate = value;
  }

  /**
   * Gets the value of the 'join_date' field.
   * @return The value of the 'join_date' field.
   */
  public java.lang.CharSequence getJoinDate() {
    return join_date;
  }


  /**
   * Sets the value of the 'join_date' field.
   * @param value the value to set.
   */
  public void setJoinDate(java.lang.CharSequence value) {
    this.join_date = value;
  }

  /**
   * Gets the value of the 'previous_logins' field.
   * @return The value of the 'previous_logins' field.
   */
  public java.lang.Integer getPreviousLogins() {
    return previous_logins;
  }


  /**
   * Sets the value of the 'previous_logins' field.
   * @param value the value to set.
   */
  public void setPreviousLogins(java.lang.Integer value) {
    this.previous_logins = value;
  }

  /**
   * Gets the value of the 'last_ip' field.
   * @return The value of the 'last_ip' field.
   */
  public java.lang.CharSequence getLastIp() {
    return last_ip;
  }


  /**
   * Sets the value of the 'last_ip' field.
   * @param value the value to set.
   */
  public void setLastIp(java.lang.CharSequence value) {
    this.last_ip = value;
  }

  /**
   * Creates a new BdPerson RecordBuilder.
   * @return A new BdPerson RecordBuilder
   */
  public static me.mh.avro.BdPerson.Builder newBuilder() {
    return new me.mh.avro.BdPerson.Builder();
  }

  /**
   * Creates a new BdPerson RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BdPerson RecordBuilder
   */
  public static me.mh.avro.BdPerson.Builder newBuilder(me.mh.avro.BdPerson.Builder other) {
    if (other == null) {
      return new me.mh.avro.BdPerson.Builder();
    } else {
      return new me.mh.avro.BdPerson.Builder(other);
    }
  }

  /**
   * Creates a new BdPerson RecordBuilder by copying an existing BdPerson instance.
   * @param other The existing instance to copy.
   * @return A new BdPerson RecordBuilder
   */
  public static me.mh.avro.BdPerson.Builder newBuilder(me.mh.avro.BdPerson other) {
    if (other == null) {
      return new me.mh.avro.BdPerson.Builder();
    } else {
      return new me.mh.avro.BdPerson.Builder(other);
    }
  }

  /**
   * RecordBuilder for BdPerson instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BdPerson>
    implements org.apache.avro.data.RecordBuilder<BdPerson> {

    private int id;
    private java.lang.CharSequence username;
    private java.lang.CharSequence email_address;
    private java.lang.CharSequence phone_number;
    private java.lang.CharSequence first_name;
    private java.lang.CharSequence last_name;
    private java.lang.CharSequence middle_name;
    private java.lang.CharSequence sex;
    private java.lang.CharSequence birthdate;
    private java.lang.CharSequence join_date;
    private java.lang.Integer previous_logins;
    private java.lang.CharSequence last_ip;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(me.mh.avro.BdPerson.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.username)) {
        this.username = data().deepCopy(fields()[1].schema(), other.username);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.email_address)) {
        this.email_address = data().deepCopy(fields()[2].schema(), other.email_address);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.phone_number)) {
        this.phone_number = data().deepCopy(fields()[3].schema(), other.phone_number);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.first_name)) {
        this.first_name = data().deepCopy(fields()[4].schema(), other.first_name);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.last_name)) {
        this.last_name = data().deepCopy(fields()[5].schema(), other.last_name);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.middle_name)) {
        this.middle_name = data().deepCopy(fields()[6].schema(), other.middle_name);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.sex)) {
        this.sex = data().deepCopy(fields()[7].schema(), other.sex);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.birthdate)) {
        this.birthdate = data().deepCopy(fields()[8].schema(), other.birthdate);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.join_date)) {
        this.join_date = data().deepCopy(fields()[9].schema(), other.join_date);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.previous_logins)) {
        this.previous_logins = data().deepCopy(fields()[10].schema(), other.previous_logins);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.last_ip)) {
        this.last_ip = data().deepCopy(fields()[11].schema(), other.last_ip);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
    }

    /**
     * Creates a Builder by copying an existing BdPerson instance
     * @param other The existing instance to copy.
     */
    private Builder(me.mh.avro.BdPerson other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.username)) {
        this.username = data().deepCopy(fields()[1].schema(), other.username);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.email_address)) {
        this.email_address = data().deepCopy(fields()[2].schema(), other.email_address);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.phone_number)) {
        this.phone_number = data().deepCopy(fields()[3].schema(), other.phone_number);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.first_name)) {
        this.first_name = data().deepCopy(fields()[4].schema(), other.first_name);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.last_name)) {
        this.last_name = data().deepCopy(fields()[5].schema(), other.last_name);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.middle_name)) {
        this.middle_name = data().deepCopy(fields()[6].schema(), other.middle_name);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.sex)) {
        this.sex = data().deepCopy(fields()[7].schema(), other.sex);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.birthdate)) {
        this.birthdate = data().deepCopy(fields()[8].schema(), other.birthdate);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.join_date)) {
        this.join_date = data().deepCopy(fields()[9].schema(), other.join_date);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.previous_logins)) {
        this.previous_logins = data().deepCopy(fields()[10].schema(), other.previous_logins);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.last_ip)) {
        this.last_ip = data().deepCopy(fields()[11].schema(), other.last_ip);
        fieldSetFlags()[11] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public int getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public me.mh.avro.BdPerson.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public me.mh.avro.BdPerson.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'username' field.
      * @return The value.
      */
    public java.lang.CharSequence getUsername() {
      return username;
    }


    /**
      * Sets the value of the 'username' field.
      * @param value The value of 'username'.
      * @return This builder.
      */
    public me.mh.avro.BdPerson.Builder setUsername(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.username = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'username' field has been set.
      * @return True if the 'username' field has been set, false otherwise.
      */
    public boolean hasUsername() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'username' field.
      * @return This builder.
      */
    public me.mh.avro.BdPerson.Builder clearUsername() {
      username = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'email_address' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmailAddress() {
      return email_address;
    }


    /**
      * Sets the value of the 'email_address' field.
      * @param value The value of 'email_address'.
      * @return This builder.
      */
    public me.mh.avro.BdPerson.Builder setEmailAddress(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.email_address = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'email_address' field has been set.
      * @return True if the 'email_address' field has been set, false otherwise.
      */
    public boolean hasEmailAddress() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'email_address' field.
      * @return This builder.
      */
    public me.mh.avro.BdPerson.Builder clearEmailAddress() {
      email_address = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'phone_number' field.
      * @return The value.
      */
    public java.lang.CharSequence getPhoneNumber() {
      return phone_number;
    }


    /**
      * Sets the value of the 'phone_number' field.
      * @param value The value of 'phone_number'.
      * @return This builder.
      */
    public me.mh.avro.BdPerson.Builder setPhoneNumber(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.phone_number = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'phone_number' field has been set.
      * @return True if the 'phone_number' field has been set, false otherwise.
      */
    public boolean hasPhoneNumber() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'phone_number' field.
      * @return This builder.
      */
    public me.mh.avro.BdPerson.Builder clearPhoneNumber() {
      phone_number = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'first_name' field.
      * @return The value.
      */
    public java.lang.CharSequence getFirstName() {
      return first_name;
    }


    /**
      * Sets the value of the 'first_name' field.
      * @param value The value of 'first_name'.
      * @return This builder.
      */
    public me.mh.avro.BdPerson.Builder setFirstName(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.first_name = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'first_name' field has been set.
      * @return True if the 'first_name' field has been set, false otherwise.
      */
    public boolean hasFirstName() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'first_name' field.
      * @return This builder.
      */
    public me.mh.avro.BdPerson.Builder clearFirstName() {
      first_name = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'last_name' field.
      * @return The value.
      */
    public java.lang.CharSequence getLastName() {
      return last_name;
    }


    /**
      * Sets the value of the 'last_name' field.
      * @param value The value of 'last_name'.
      * @return This builder.
      */
    public me.mh.avro.BdPerson.Builder setLastName(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.last_name = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'last_name' field has been set.
      * @return True if the 'last_name' field has been set, false otherwise.
      */
    public boolean hasLastName() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'last_name' field.
      * @return This builder.
      */
    public me.mh.avro.BdPerson.Builder clearLastName() {
      last_name = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'middle_name' field.
      * @return The value.
      */
    public java.lang.CharSequence getMiddleName() {
      return middle_name;
    }


    /**
      * Sets the value of the 'middle_name' field.
      * @param value The value of 'middle_name'.
      * @return This builder.
      */
    public me.mh.avro.BdPerson.Builder setMiddleName(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.middle_name = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'middle_name' field has been set.
      * @return True if the 'middle_name' field has been set, false otherwise.
      */
    public boolean hasMiddleName() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'middle_name' field.
      * @return This builder.
      */
    public me.mh.avro.BdPerson.Builder clearMiddleName() {
      middle_name = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'sex' field.
      * @return The value.
      */
    public java.lang.CharSequence getSex() {
      return sex;
    }


    /**
      * Sets the value of the 'sex' field.
      * @param value The value of 'sex'.
      * @return This builder.
      */
    public me.mh.avro.BdPerson.Builder setSex(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.sex = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'sex' field has been set.
      * @return True if the 'sex' field has been set, false otherwise.
      */
    public boolean hasSex() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'sex' field.
      * @return This builder.
      */
    public me.mh.avro.BdPerson.Builder clearSex() {
      sex = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'birthdate' field.
      * @return The value.
      */
    public java.lang.CharSequence getBirthdate() {
      return birthdate;
    }


    /**
      * Sets the value of the 'birthdate' field.
      * @param value The value of 'birthdate'.
      * @return This builder.
      */
    public me.mh.avro.BdPerson.Builder setBirthdate(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.birthdate = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'birthdate' field has been set.
      * @return True if the 'birthdate' field has been set, false otherwise.
      */
    public boolean hasBirthdate() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'birthdate' field.
      * @return This builder.
      */
    public me.mh.avro.BdPerson.Builder clearBirthdate() {
      birthdate = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'join_date' field.
      * @return The value.
      */
    public java.lang.CharSequence getJoinDate() {
      return join_date;
    }


    /**
      * Sets the value of the 'join_date' field.
      * @param value The value of 'join_date'.
      * @return This builder.
      */
    public me.mh.avro.BdPerson.Builder setJoinDate(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.join_date = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'join_date' field has been set.
      * @return True if the 'join_date' field has been set, false otherwise.
      */
    public boolean hasJoinDate() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'join_date' field.
      * @return This builder.
      */
    public me.mh.avro.BdPerson.Builder clearJoinDate() {
      join_date = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'previous_logins' field.
      * @return The value.
      */
    public java.lang.Integer getPreviousLogins() {
      return previous_logins;
    }


    /**
      * Sets the value of the 'previous_logins' field.
      * @param value The value of 'previous_logins'.
      * @return This builder.
      */
    public me.mh.avro.BdPerson.Builder setPreviousLogins(java.lang.Integer value) {
      validate(fields()[10], value);
      this.previous_logins = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'previous_logins' field has been set.
      * @return True if the 'previous_logins' field has been set, false otherwise.
      */
    public boolean hasPreviousLogins() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'previous_logins' field.
      * @return This builder.
      */
    public me.mh.avro.BdPerson.Builder clearPreviousLogins() {
      previous_logins = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'last_ip' field.
      * @return The value.
      */
    public java.lang.CharSequence getLastIp() {
      return last_ip;
    }


    /**
      * Sets the value of the 'last_ip' field.
      * @param value The value of 'last_ip'.
      * @return This builder.
      */
    public me.mh.avro.BdPerson.Builder setLastIp(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.last_ip = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'last_ip' field has been set.
      * @return True if the 'last_ip' field has been set, false otherwise.
      */
    public boolean hasLastIp() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'last_ip' field.
      * @return This builder.
      */
    public me.mh.avro.BdPerson.Builder clearLastIp() {
      last_ip = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BdPerson build() {
      try {
        BdPerson record = new BdPerson();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.username = fieldSetFlags()[1] ? this.username : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.email_address = fieldSetFlags()[2] ? this.email_address : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.phone_number = fieldSetFlags()[3] ? this.phone_number : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.first_name = fieldSetFlags()[4] ? this.first_name : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.last_name = fieldSetFlags()[5] ? this.last_name : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.middle_name = fieldSetFlags()[6] ? this.middle_name : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.sex = fieldSetFlags()[7] ? this.sex : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.birthdate = fieldSetFlags()[8] ? this.birthdate : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.join_date = fieldSetFlags()[9] ? this.join_date : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.previous_logins = fieldSetFlags()[10] ? this.previous_logins : (java.lang.Integer) defaultValue(fields()[10]);
        record.last_ip = fieldSetFlags()[11] ? this.last_ip : (java.lang.CharSequence) defaultValue(fields()[11]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BdPerson>
    WRITER$ = (org.apache.avro.io.DatumWriter<BdPerson>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BdPerson>
    READER$ = (org.apache.avro.io.DatumReader<BdPerson>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.id);

    if (this.username == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeString(this.username);
    }

    if (this.email_address == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeString(this.email_address);
    }

    if (this.phone_number == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeString(this.phone_number);
    }

    if (this.first_name == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeString(this.first_name);
    }

    if (this.last_name == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeString(this.last_name);
    }

    if (this.middle_name == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeString(this.middle_name);
    }

    if (this.sex == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeString(this.sex);
    }

    if (this.birthdate == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeString(this.birthdate);
    }

    if (this.join_date == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeString(this.join_date);
    }

    if (this.previous_logins == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeInt(this.previous_logins);
    }

    if (this.last_ip == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeString(this.last_ip);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readInt();

      if (in.readIndex() != 0) {
        in.readNull();
        this.username = null;
      } else {
        this.username = in.readString(this.username instanceof Utf8 ? (Utf8)this.username : null);
      }

      if (in.readIndex() != 0) {
        in.readNull();
        this.email_address = null;
      } else {
        this.email_address = in.readString(this.email_address instanceof Utf8 ? (Utf8)this.email_address : null);
      }

      if (in.readIndex() != 0) {
        in.readNull();
        this.phone_number = null;
      } else {
        this.phone_number = in.readString(this.phone_number instanceof Utf8 ? (Utf8)this.phone_number : null);
      }

      if (in.readIndex() != 0) {
        in.readNull();
        this.first_name = null;
      } else {
        this.first_name = in.readString(this.first_name instanceof Utf8 ? (Utf8)this.first_name : null);
      }

      if (in.readIndex() != 0) {
        in.readNull();
        this.last_name = null;
      } else {
        this.last_name = in.readString(this.last_name instanceof Utf8 ? (Utf8)this.last_name : null);
      }

      if (in.readIndex() != 0) {
        in.readNull();
        this.middle_name = null;
      } else {
        this.middle_name = in.readString(this.middle_name instanceof Utf8 ? (Utf8)this.middle_name : null);
      }

      if (in.readIndex() != 0) {
        in.readNull();
        this.sex = null;
      } else {
        this.sex = in.readString(this.sex instanceof Utf8 ? (Utf8)this.sex : null);
      }

      if (in.readIndex() != 0) {
        in.readNull();
        this.birthdate = null;
      } else {
        this.birthdate = in.readString(this.birthdate instanceof Utf8 ? (Utf8)this.birthdate : null);
      }

      if (in.readIndex() != 0) {
        in.readNull();
        this.join_date = null;
      } else {
        this.join_date = in.readString(this.join_date instanceof Utf8 ? (Utf8)this.join_date : null);
      }

      if (in.readIndex() != 0) {
        in.readNull();
        this.previous_logins = null;
      } else {
        this.previous_logins = in.readInt();
      }

      if (in.readIndex() != 0) {
        in.readNull();
        this.last_ip = null;
      } else {
        this.last_ip = in.readString(this.last_ip instanceof Utf8 ? (Utf8)this.last_ip : null);
      }

    } else {
      for (int i = 0; i < 12; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readInt();
          break;

        case 1:
          if (in.readIndex() != 0) {
            in.readNull();
            this.username = null;
          } else {
            this.username = in.readString(this.username instanceof Utf8 ? (Utf8)this.username : null);
          }
          break;

        case 2:
          if (in.readIndex() != 0) {
            in.readNull();
            this.email_address = null;
          } else {
            this.email_address = in.readString(this.email_address instanceof Utf8 ? (Utf8)this.email_address : null);
          }
          break;

        case 3:
          if (in.readIndex() != 0) {
            in.readNull();
            this.phone_number = null;
          } else {
            this.phone_number = in.readString(this.phone_number instanceof Utf8 ? (Utf8)this.phone_number : null);
          }
          break;

        case 4:
          if (in.readIndex() != 0) {
            in.readNull();
            this.first_name = null;
          } else {
            this.first_name = in.readString(this.first_name instanceof Utf8 ? (Utf8)this.first_name : null);
          }
          break;

        case 5:
          if (in.readIndex() != 0) {
            in.readNull();
            this.last_name = null;
          } else {
            this.last_name = in.readString(this.last_name instanceof Utf8 ? (Utf8)this.last_name : null);
          }
          break;

        case 6:
          if (in.readIndex() != 0) {
            in.readNull();
            this.middle_name = null;
          } else {
            this.middle_name = in.readString(this.middle_name instanceof Utf8 ? (Utf8)this.middle_name : null);
          }
          break;

        case 7:
          if (in.readIndex() != 0) {
            in.readNull();
            this.sex = null;
          } else {
            this.sex = in.readString(this.sex instanceof Utf8 ? (Utf8)this.sex : null);
          }
          break;

        case 8:
          if (in.readIndex() != 0) {
            in.readNull();
            this.birthdate = null;
          } else {
            this.birthdate = in.readString(this.birthdate instanceof Utf8 ? (Utf8)this.birthdate : null);
          }
          break;

        case 9:
          if (in.readIndex() != 0) {
            in.readNull();
            this.join_date = null;
          } else {
            this.join_date = in.readString(this.join_date instanceof Utf8 ? (Utf8)this.join_date : null);
          }
          break;

        case 10:
          if (in.readIndex() != 0) {
            in.readNull();
            this.previous_logins = null;
          } else {
            this.previous_logins = in.readInt();
          }
          break;

        case 11:
          if (in.readIndex() != 0) {
            in.readNull();
            this.last_ip = null;
          } else {
            this.last_ip = in.readString(this.last_ip instanceof Utf8 ? (Utf8)this.last_ip : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










