kafka:
  replicas: 3 #1
  config:
    offsetsTopicReplicationFactor: 3 #1
    transactionStateLogReplicationFactor: 3 #1
    transactionStateLogMinIsr: 1 #2
    logMessageFormatVersion: "3.7"
    interBrokerProtocolVersion: "3.7"
    logCleanupPolicy: compact

  storage:
    type: ephemeral
    size: 10Gi
    deleteClaim: false
    class: netapp-qtree
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 500Mi

zookeeper:
  replicas: 3
  storage:
    type: ephemeral
    size: 10Gi
    deleteClaim: false
    class: netapp-qtree
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 500Mi


tlsSidecar:
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi


topicOperator:
  resources:
    limits:
      cpu: 500m
      memory: 300Mi
    requests:
      cpu: 100m
      memory: 100Mi


userOperator:
  resources:
    limits:
      cpu: 500m
      memory: 300Mi
    requests:
      cpu: 100m
      memory: 100Mi


kafkaExporter:
  resources:
    limits:
      cpu: 500m
      memory: 700Mi
    requests:
      cpu: 100m
      memory: 500Mi