connectors:

  - name: weather_source_connector_v0
    class: com.custom.kafka.connect.WeatherAPIConnector
    tasksMax: 1
    config:
      open.weather.api.key: 8210a492417fb274440f643f9fb1ff6b
      cities: Lund,Oslo,Stockholm,Copenhagen,Helsinki
      kafka.topic: weather-data-v0
      value.converter: org.apache.kafka.connect.storage.StringConverter
      key.converter: org.apache.kafka.connect.storage.StringConverter
      is.struct: false
      min.insync.replicas: 1

  - name: weather_source_connector_v1
    class: com.custom.kafka.connect.WeatherAPIConnector
    tasksMax: 2
    config:
      open.weather.api.key: 8210a492417fb274440f643f9fb1ff6b
      cities: Berlin,Rome,Prague,Vienna,Budapest
      kafka.topic: weather-data-v1
      is.struct: false
      min.insync.replicas: 1

  - name: weather_source_connector_v2
    class: com.custom.kafka.connect.WeatherAPIConnector
    tasksMax: 3
    config:
      open.weather.api.key: 8210a492417fb274440f643f9fb1ff6b
      cities: Delhi,Osaka,Dhaka,Shanghai,Singapore
      kafka.topic: weather-data-v2
      is.struct: true
      min.insync.replicas: 1    