apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '9404'
    prometheus.io/scrape: 'true'
  name: {{ .Values.global.kafkaClusterName }}-kafka-exporter-svc
  labels:
    strimzi.io/discovery: 'true'
    strimzi.io/kind: Kafka
    strimzi.io/name: {{ .Values.global.kafkaClusterName }}-kafka-exporter
spec:
  ports:
  - port: 9404
    name: prometheus
    protocol: TCP
  selector:
    strimzi.io/kind: Kafka
    strimzi.io/cluster: {{ .Values.global.kafkaClusterName }}
    strimzi.io/name: {{ .Values.global.kafkaClusterName }}-kafka-exporter
  type: NodePort
status:
  loadBalancer: {}
