config:
  connectTopicReplicas: -1 # -1 means it will use the default replication factor configured in the broker
  enableKafkaConnectorRes: true

connect:
  log:
    level: INFO

additional:

replicas: 3

jvmMemory:
  max: 1500m # 75% of pod memory is recommended
  min: 512m

jvmOptions:
  gcLoggingEnabled: false

image:
  name: mehdihasan/demo-kafka-connect
  tag: "0.42.0-strimzi-0.42.0-kafka-3.7.1"

resources:
  limits:
    cpu: 500m
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 500Mi