/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.test.kafka.model;
@org.apache.avro.specific.AvroGenerated
public enum Color implements org.apache.avro.generic.GenericEnumSymbol<Color> {
  GREEN, BLUE, PURPLE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Color\",\"namespace\":\"com.test.kafka.model\",\"symbols\":[\"GREEN\",\"BLUE\",\"PURPLE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
