/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.test.kafka.model;
@org.apache.avro.specific.AvroGenerated
public enum DesignType implements org.apache.avro.generic.GenericEnumSymbol<DesignType> {
  NONE, SUITCASE, CAR, WARNING  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"DesignType\",\"namespace\":\"com.test.kafka.model\",\"symbols\":[\"NONE\",\"SUITCASE\",\"CAR\",\"WARNING\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
