/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.test.kafka.model;
@org.apache.avro.specific.AvroGenerated
public enum ProductType implements org.apache.avro.generic.GenericEnumSymbol<ProductType> {
  TSHIRT, DESIGN  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ProductType\",\"namespace\":\"com.test.kafka.model\",\"symbols\":[\"TSHIRT\",\"DESIGN\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
